import express from "express";
const router = express.Router();
import userControllers from "../controllers/userControllers.js";
router.post("/add", userControllers.createUser);
router.get("/", userControllers.getAllUser);
router.get("/:ID", userControllers.getUserByParam);
router.put("/:ID", userControllers.updateUserById);
router.delete("/:ID", userControllers.deleteUserById);
router.post("/login", userControllers.login, userControllers.deleteUserById);
export default router;